- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enabling nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: installing packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - nodejs
  - mysql

- name: adding user
  ansible.builtin.user:
    name: expense

- name: run app-common file
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-common

# - name: install npm dependencies
#   ansible.builtin.command: npm install
#   args:
#     chdir: /app

- name: copying backend service file to backend server
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
  notify:
  - restarting backend 

- name: Install bottle python package
  ansible.builtin.pip:
    name: 
    - PyMySql
    - cryptography
    executable: pip3.9

- name: import data into mysql
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ login_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  notify:
  - restarting backend

- name: start and enable backend service
  tags:
  - deployment
  ansible.builtin.service:
    name: backend
    state: restarted
    enabled: yes