- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: starting and enabling nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: run common app-common file
  ansible.builtin.import_role:
    name: common
    tasks_from: app-common

- name: copying expense config file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restaring nginx
  
# - name: restaring nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted      